#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


#  Source utility functions.
source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"


#  On slave/serving gears, need to do the install as part of deploy
#  so check if its needed. Just ensure the custom Node[.js] version is
#  installed.
ensure_node_is_installed



#Install bower and bower install
if [ ! -d $OPENSHIFT_NODEJS_DIR/node_modules/bower ]
then
    cd $OPENSHIFT_NODEJS_DIR
    npm install bower
fi

cd $OPENSHIFT_HOMEDIR/app-root/repo
HOME=$OPENSHIFT_REPO_DIR bower install
cd $OPENSHIFT_HOMEDIR

